# Generated by Django 4.2.7 on 2023-11-16 01:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0002_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
